apiVersion: v1
kind: Service
metadata:
  name: debian-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: ssh
    protocol: TCP
    port: 22
  selector:
    kubevirt.io/domain: debian
  type: NodePort